name: C++ with CMake CI

on: [push, pull_request]

jobs:
  checker:
  SHM:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Run check.sh
      working-directory: shm
      run: |
        chmod +x check.sh
        ./check.sh CMakeLists.txt

    - name: mkdir shm/build
      run: mkdir shm/build
    - name: Compile
      working-directory: shm/build
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: shm/build
      run: ctest -V

